### ISSUE TITLE
SSH transport fails when using 'password'

### ISSUE THREAD

**Issue by TimNZ** [megahertz/electron-simple-publisher#10]
Great work for simplifying auto updates, thank you so much.
electron-builder and the others are so poorly documented and complex.

Had to change transports/ssh.js.
Faulty boolean logic for private key checks when 'password' is specified in publisher.json/options

```
if (options.usePrivateKey || !options.privateKeyPath || !options.privateKey) {
      // options.privateKeyPath = path.join(os.homedir(), '.ssh', 'id_rsa');
    }
    if (options.privateKeyPath) {
      // options.privateKey = fs.readFileSync(options.privateKeyPath, 'utf-8');
    }
```

**Comment by TimNZ** [comment]
Thanks!

**Comment by megahertz** [comment]
Thank you for the report. It was very ugly bug.
