### ISSUE TITLE
add-assets-info.js update for OS X

### ISSUE THREAD

**Issue by TimNZ** [megahertz/electron-simple-publisher#11]
Changed:

```
  'darwin-x64': {
    dir: '',
    assets: {
      update: 'mac/{version}-mac.zip',
      install: '{version}.dmg',
      metaFile: null
    }
  },
```

to

```
  'darwin-x64': {
    dir: 'mac',
    assets: {
      update: '{version}-mac.zip',
      install: '{version}.dmg',
      metaFile: null
    }
  },
```

**Comment by megahertz** [comment]
The latest electron-builder creates dmg file in dist folder instead of dist/mac

**Comment by TimNZ** [comment]
Sorry.  I was sure I was on the latest and am not.
Will try later today and close issue once confirmed, though I doubt you are wrong :)

**Comment by megahertz** [comment]
It seems that builder has been updated again and now it contains different paths. I'll update it in a day.

**Comment by TimNZ** [comment]
Thanks so much.
electron-builder is very handy, but the owner is poor at managing the project overall.
Poor docs and regularly changing how things work.
