### ISSUE TITLE
Publishing from different OS

### ISSUE THREAD

**Issue by sin6pi7** [megahertz/electron-simple-publisher#12]
Hello @megahertz,
first of all - great repo!
I am using CI servers to build and publish distributable electron packages to s3 from different operating systems (win, osx, linux). This process makes 3 different updates.json being uploaded to s3, which with current version of electron-simple-publisher will only keep the last uploaded one having overwritten previous ones, which in turn makes updates possible only for one OS. My current workaround for overriding is as follow:
- build with electron-builder,
- use electron-simple-publisher to publish locally,
- rename updates.json to updates-${os_name}.json,
- publish dist/publish directory to s3 manually,
- init electron-simple-updater with path to updates-${os_name}.json.

It works, but it makes the process longer by copying files locally and more error-prone by requiring me to rewrite publishing to s3.
Would it be possible for electron-simple-publisher to support such a case?

**Comment by megahertz** [comment]
Hi. You can use s3 transport and publish to the same bucket, updates.json will be merged automatically.
