### ISSUE TITLE
Support custom transport

### ISSUE THREAD

**Issue by altjz** [megahertz/electron-simple-publisher#17]
Hi, I really love the transport design, I used to write a lot scripts but now just a few config. Thanks for providing such awesome tool.

Many web cloud services besides AWS s3 provide sdk for node.js. And I know it is not possible to cover all transport services. 
So I wonder if `electron-simple-publisher` could support extend custom transport.  

For example, I write a new transport JS file same as lib/transport/, then use it in publisher.json.

Furthermore, I could create a custom transport and make it a individual module, then other one just install this module and config it in publisher.json.

**Comment by megahertz** [comment]
Hi. You can set the transport.module option to:
- npm package name
-  '{cwd}/path-to-local-transport.js'. the {cwd} template will be replaced to the current working directory (usual project's root)
