### ISSUE TITLE
Transport Module FTP

### ISSUE THREAD

**Issue by abalad** [megahertz/electron-simple-publisher#2]
Is it possible to create the transport module to use FTP?

**Comment by megahertz** [comment]
Yes, I have a plan for it. But I don't know when I'll be able to add this transport.

**Comment by megahertz** [comment]
At this moment you can use new local transport and then upload files manually or using tools like ncftpput. I'm going to add ftp support later

**Comment by amazighezed** [comment]
hello,
please, can we use your solution for gitLab
thank you

**Comment by megahertz** [comment]
@amazighezed It seems that GitLab API is similar to github API, but I have no time for making the GitLab transport now. I can recommend you to use another file hosting or you can try to make a GitLab transport protocol by yourself.

**Comment by amazighezed** [comment]
ok thank you so much
