### ISSUE TITLE
Building for 32 Bit version

### ISSUE THREAD

**Issue by hakikihacioglu** [megahertz/electron-simple-publisher#24]
Hi,

Simple publisher works without any problems with 
`  
"win": {
    "target": "squirrel"
  }
`
for windows 64Bit. How can I build with squirrel for 32 Bit versions of windows.

Thank you

**Comment by megahertz** [comment]
- build ia32 with electron builder
- run publish command with argument win32-ia32

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
