### ISSUE TITLE
crashing on publish

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-publisher#25]
please see this

`> publish

Could not initialize a transport. Check transport.module option.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! filmplicity@0.0.3 publish: `publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filmplicity@0.0.3 publish script 'publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the filmplicity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs filmplicity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls filmplicity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Scratch\Filmplicity\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! filmplicity@0.0.3 release: `npm run dist && npm run publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filmplicity@0.0.3 release script 'npm run dist && npm run publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the filmplicity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dist && npm run publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs filmplicity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls filmplicity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Scratch\Filmplicity\npm-debug.log`

for some reason it builds it, but then crashes when it tries to publish it please help

**Comment by megahertz** [comment]
It shows you the actual problem. Your publisher config is wrong.

**Comment by Custardcs** [comment]
but i copied what you wrote down in your git hub

`{
  "transport": {
    "module": "github",
    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "fields": { // Additional fields which will be added to updates.json
    "readme": "The Third version"
  }
}`

is this not correct?

**Comment by megahertz** [comment]
It seems correct. Try to run publish publisher.json

**Comment by Custardcs** [comment]
i tried it and it comes back with 

C:\Scratch\Filmplicity>npm run publish

> filmplicity@0.0.3 publish C:\Scratch\Filmplicity
> publish

Could not initialize a transport. Check transport.module option.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! filmplicity@0.0.3 publish: `publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filmplicity@0.0.3 publish script 'publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the filmplicity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs filmplicity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls filmplicity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Scratch\Filmplicity\npm-debug.log

C:\Scratch\Filmplicity>

same error,

and in my package.json i have

  "updater": {
    "url": "https://github.com/Custardcs/Filmplicity/update/updates.json"
  },

**Comment by Custardcs** [comment]
could it be because its a private repo?

**Comment by megahertz** [comment]
I don't understand why your config isn't read. But with private repository you'll get an error later, when you try to run update.

**Comment by Custardcs** [comment]
is the publisher.json supposed to be in root? or in app/publisher.json i added the other two options that i see you have in your wiki

{
  "transport": {
    "module": "github",
    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "repository" : "Custardcs/Filmplicity",
    "updatesJsonPath": "update/updates.json"
  },
  "fields": { // Additional fields which will be added to updates.json
    "readme": "The Third version"
  }
}

**Comment by Custardcs** [comment]
alright i managed to fix the problem, i removed everything and type it in again. deleted and added it to the root and the ./app

and it seems to be uploading now.. so its progress :|

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
