### ISSUE TITLE
32bit

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-publisher#26]
hi, so i have been reading up on some of the things that were being used and i see you said to a previous message about using

build --ia32 but it doesn't work :|

also you are using target = squirrel.windows they say its depreciated..

so if i use nsis can i still use your auto updating?

**Comment by megahertz** [comment]
Hi. Last time I used win32-ia32 it works correctly. And electron-builder always displays warning when you build squirrel ia32 build. As for nsis, electron-simple-updater doesn't support it.

**Comment by Custardcs** [comment]
i had to use     "dist": "build --arch=all", in order for it to work. noone explain this :| lol but anyhow thanks bud ill keep the squirrell and all is building and stuff and if i publish

do i just do npm run publish? and it will push both 32 and 64 to github?

**Comment by megahertz** [comment]
The publisher uploads only one build at once. So you need to run it for each build.

**Comment by Custardcs** [comment]
but what happens with the update.json then it gets over written each time? it doesnt combine the scripts?

does this mean i have to manually change it?

**Comment by megahertz** [comment]
update.json will be merged

**Comment by Custardcs** [comment]
alright well something is not working, because i published and it overwrote it. and i am now getting another error i dont understand what i am doing wrong. i uploaded version 0.0.1 and 0.0.2

i ran version 0.0.1 and it says (Update for win32-x64-prod-v0.0.1 is not available)
is there something i'm missing?

**Comment by Custardcs** [comment]
when it finished publishing it got this

Could not get updates.json. You can ignore this warning if you run this command for the first time. A hosting response is:
404 {"error":"Not Found"}
All releases have been successfully published

is this why it is overwriting the json?

**Comment by megahertz** [comment]
Yes, that's why it's not merged. Publisher can't determine the json path. You can set it through updatesJsonUrl option.

**Comment by Custardcs** [comment]
your comment says

**Comment by megahertz** [comment]
First of all, make sure that your app can retrieve updates.json correctly. Because you've received 404 when publishing I can assume that something wrong with update.url option.

**Comment by Custardcs** [comment]
well its because its a private repo? im assuming? and if i make it public i see its releasing the source code with the release and i cant do that. soo is there a way i can get it to work between the two?

**Comment by megahertz** [comment]
You can create a public repo for releases only.

**Comment by Custardcs** [comment]
Thats fine i dont mind creating a public one but then when i publish it has the source code with the release and i dont want the source available? so how i i stop it from releasing the source when i run

npm run publish

**Comment by megahertz** [comment]
What do you mean? Publisher can only upload binaries, not source.

**Comment by Custardcs** [comment]
i created a public repo and tried to npm run publish and when it was done this is what is has


![capture](https://user-images.githubusercontent.com/14811199/28678971-16c67e56-72f2-11e7-9c7b-e4f10e082998.PNG)

i can not have the source available

**Comment by megahertz** [comment]
Sure, github creates it for each release, even if the repo is empty.

**Comment by Custardcs** [comment]
but then anyone can download the source? or is it the source of the empty repo?

**Comment by megahertz** [comment]
Just open the archive

**Comment by Custardcs** [comment]
alright ill try it now bud.. thank you for all your help.

**Comment by Custardcs** [comment]
Hi bro tried the 32 bit publish doesnt work

C:\scratch\Filmplicity>npm run publish32

> filmplicity@0.0.7 publish32 C:\scratch\Filmplicity
> publish win-ia32

Unknown build type win-ia32

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish32"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! filmplicity@0.0.7 publish32: `publish win-ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filmplicity@0.0.7 publish32 script 'publish win-ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the filmplicity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     publish win-ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs filmplicity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls filmplicity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\scratch\Filmplicity\npm-debug.log

C:\scratch\Filmplicity>

**Comment by megahertz** [comment]
win32-ia32

14 авг 2017 г. 7:46 пользователь "JarHeaD" <notifications@github.com>
написал:

**Comment by Custardcs** [comment]
i have done that too

C:\Scratch\Filmplicity>npm run publish32

> filmplicity@0.0.7 publish32 C:\Scratch\Filmplicity
> publish win32-ia32

File C:\Scratch\Filmplicity\dist\win-ia32\Filmplicity Setup 0.0.7-ia32.exe doesn't exists. You can try to check if:
 - electron-builder successfully made a build
 - electron-builder and electron-simple-publisher are up to date
 - if nothing helps please create a new github issue. Don't forget to include electron-builder version to the bug report.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish32"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! filmplicity@0.0.7 publish32: `publish win32-ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filmplicity@0.0.7 publish32 script 'publish win32-ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the filmplicity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     publish win32-ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs filmplicity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls filmplicity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Scratch\Filmplicity\npm-debug.log

C:\Scratch\Filmplicity>

**Comment by Custardcs** [comment]
i see it is looking for 

Filmplicity Setup 0.0.7-ia32.exe doesn't exists

but when i use the dist32 which builds it in the correct folder win-ia32

but with the name of Filmplicity Setup 0.0.7.exe

**Comment by megahertz** [comment]
What's electron-builder version?

**Comment by Custardcs** [comment]
"electron-builder": "latest",

**Comment by megahertz** [comment]
Try the latest version of publisher

**Comment by Custardcs** [comment]
0.4.7? its still doing the same thing :|

**Comment by megahertz** [comment]
Please provide console output when using this version

**Comment by Custardcs** [comment]
its still building the file with  Setup 0.0.7.exe isnt it supposed to build it with the  Setup 0.0.7.exe-ia32?

**Comment by megahertz** [comment]
In my environment it can use both forms, with -ia32 and without. Try remove node-modules and than `npm i`

**Comment by Custardcs** [comment]
alright yes
its working ... its publishing if there is any other issue ill let you know 💃
