### ISSUE TITLE
(SOLVED) Failed at the phantomjs@1.9.20 install script.

### ISSUE THREAD

**Issue by rafaelbuiu** [megahertz/electron-simple-publisher#28]
One of the electron-simple-publisher dependencies has a missing dependency on ESP install process.

PhantomJS installation fails when throws this error:
`Error: Cannot find module 'is-my-json-valid'`

The solution is to install the module before trying to install electron-simple-builder
`npm install --save-dev is-my-json-valid`

**Comment by megahertz** [comment]
I've not seen this problem with phantom, but thanks for solution.
