### ISSUE TITLE
UPDATE.JSON

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-publisher#29]
hey bud small bug i found. when i release 64 bit it will update the 

{
  "win32-x64-prod": {
    "update": "https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.25",
    "install": "https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.25/Filmplicity.Setup.0.0.25.exe",
    "version": "0.0.25"
  },
then i run the release32 bit and it changes the 64 bit number to 24
 and sets 32 to this

  "win32-ia32-prod": {
    "update": "https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-ia32-prod-v0.0.25",
    "install": "https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-ia32-prod-v0.0.25/Filmplicity.Setup.0.0.25.exe",
    "version": "0.0.25"
  }

its weird so i have to manually edit the numbers again

**Comment by megahertz** [comment]
Hi. Sometimes github doesn't update update.json immediately. In this situation publisher receives old version of updates.json and can override some value. Unfortunately, I have no idea how to prevent it. But fortunately that's not very common.
