### ISSUE TITLE
Grouping multi-platform builds into single release on Github Releases?

### ISSUE THREAD

**Issue by danenania** [megahertz/electron-simple-publisher#30]
Hi, thanks for your work on this lib--it works great and has saved a huge amount of time!

I noticed then when I do a cross-platform publish, like `publish darwin win32 linux` using the Github transport, that three separate releases are created. Is there any way to accomplish (or plans to support) the ability to group all platform archives into a single release per version? This seems to be a bit more standard in terms of how most OSS projects are dealing with releases on Github.

**Comment by megahertz** [comment]
Hi. I tried to use a single release earlier, but unfortunately it leads to problem with both windows 32 and 64 builds in the same release, that's why I decided to separate it.
