### ISSUE TITLE
Error "Unknown build type publisher.js-x64"

### ISSUE THREAD

**Issue by SimplyAhmazing** [megahertz/electron-simple-publisher#31]
I get this error,

```
{ command: 'publish',
  builds: [ 'publisher.js' ],
  fields: {},
  transport: {} }
Unknown build type publisher.js-x64
````

After reading the source code and placing cosole.log, The error occurs [here](https://github.com/megahertz/electron-simple-publisher/blob/dd992c1377c10309f456e0d35a698ab4317d0580/lib/utils/add-assets-info.js#L49):

```
function addAssetsInfo(build, options) {
  const name = `${build.platform}-${build.arch}`;
  const meta = ASSETS_DATA[name];
  if (!meta) {
    throw new Error(`Unknown build type ${name}`);
  }
```

And I traced the `build.platform` containing the name of the config file to [this](https://github.com/megahertz/electron-simple-publisher/blob/c93915b9f43a57b86e592779b1eba3013c449334/lib/utils/get-options-from-cli.js#L54) location:

```
options.builds = args.filter(a => Boolean(a));
```

Where a is the list of command line arguments.

**Comment by SimplyAhmazing** [comment]
I ran it with `./node_modules/.bin/publish publishers.js`

**Comment by megahertz** [comment]
Try `./node_modules/.bin/publish publish publishers.js`

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
