### ISSUE TITLE
Transport module FTP: looks up updates.json on port 80

### ISSUE THREAD

**Issue by orotti13** [megahertz/electron-simple-publisher#34]
Hi. There's a problem. Electron simple publisher tries to get updates.json on port 80 even though I use FTP and have specified another port. Here's my publisher.json:
```
{
  "transport": {
    "module": "ftp",
    "host": "localhost",
    "port": 21,
    "user": "user",
    "password": "password",
    "remotePath": "/publish",
    "remoteUrl": "ftp://localhost/publish"
  }
}
```
package.json:
```
"updater": {
  "url": "ftp://localhost/updates.json"
}
```

When I fire up ./node_modules/.bin/publish I get the following error after the successful upload of setup files:
```
connect ECONNREFUSED 127.0.0.1:80
```
I tried to read provided logs but there was no useful information there. Is this a bug or expected behavior?

**Comment by megahertz** [comment]
Hi @orotti13 It's not possible to use FTP for application update. FTP can be used only for builds publishing.
