### ISSUE TITLE
Armv7l + mwl

### ISSUE THREAD

**Issue by lesmoutonssauvages** [megahertz/electron-simple-publisher#38]
Hi Megahertz, 

Many thanks for yours "simple" publisher and updater 🥇 

* * *

I test and dont want make a pr for so small :  electron-simple-publisher/lib/utils/add-assets-info.js
```js 
'linux-armv7l': {
  install: '{name}-{version}-armv7l.AppImage',
  metaFile: null,
  update: '{name}-{version}-armv7l.AppImage'
}
```
worked for me.

* * *

My question regarding mwl according to [electron.build -mwl](https://www.electron.build/multi-platform-build), cause i want to publish all artifacts in one line expect with something ugly like that : 
`
"publish": "publish darwin-x64 win32 linux-armv7l",
`
Have you plan something on that ?

* * *

Thanks

**Comment by megahertz** [comment]
Hi @lesmoutonssauvages. Thanks again for your PR. 

As for you question about `publish darwin-x64 win32 linux-armv7l`, do you mean something like `publish all` which searches for available builds?
