### ISSUE TITLE
File with mask 0.0.0-full.nupkg is not found

### ISSUE THREAD

**Issue by abalad** [megahertz/electron-simple-publisher#4]
When performing a publication without parameters it generates this message, and only updates updates.json

C:\Users\Maicon\Documents\Sistemas\MedicSolution>npm run el:publish

> medic-solution@0.0.0 el:publish C:\Users\Maicon\Documents\Sistemas\MedicSolution
> publish

File with mask 0.0.0-full.nupkg is not found at C:\Users\Maicon\Documents\Sistemas\MedicSolution\dist\win
File with mask 0.0.0.exe is not found at C:\Users\Maicon\Documents\Sistemas\MedicSolution\dist\win
All releases have been successfully published

**Comment by megahertz** [comment]
Could you provide your package.json?

**Comment by megahertz** [comment]
https://github.com/megahertz/electron-simple-publisher/issues/6#issuecomment-269153537
