### ISSUE TITLE
Need some information

### ISSUE THREAD

**Issue by fbaldo31** [megahertz/electron-simple-publisher#41]
Hi before installing it and making test i would like to know if 
- File Macro are supported ? [Doc](https://www.electron.build/file-patterns#file-macros)
- environment variable from electron-builder are available like `${env.ENV_NAME}` we can add to electron-builder.env ?

Thanks

**Comment by megahertz** [comment]
No. Why do you need these features?

**Comment by fbaldo31** [comment]
It is convenient to tag releases easily.
Thanks for information, i can close

**Comment by megahertz** [comment]
Beta version support platform, arch and channel templates in some places to point to the specific updates.json
