### ISSUE TITLE
Option --path not work

### ISSUE THREAD

**Issue by abalad** [megahertz/electron-simple-publisher#5]
I'm passing the --path argument to change the path where it should capture the dist files, but it does not take that new path.

```
C:\Users\Maicon\Documents\Sistemas\MedicSolution>publish --path ./artifacts/installers/packaged/win
ENOENT: no such file or directory, scandir 'C:\Users\Maicon\Documents\Sistemas\MedicSolution\dist\win'
```

**Comment by giacgbj** [comment]
Duplicates #1.

**Comment by megahertz** [comment]
https://github.com/megahertz/electron-simple-publisher/issues/6#issuecomment-269153537 and #1
